### ISSUE TITLE
Learn Rest API Design (Semih)

### ISSUE THREAD

**Issue by semihYILMAZ37** [bounswe/bounswe2024group5#109]
### Issue Description

learn tthe basics and best practices of Rest API design.

### Tasks

- [x] Basics of Rest API design
- [x] Best Practices of Rest API design
- [x] Security of Rest API

### Estimated Time

300

### Deadline

16/04/2024

### Reviewer

no reviewer

**Comment by semihYILMAZ37** [comment]
all tasks and the research has done
