### ISSUE TITLE
Initiate the Customer Milestone 2 Report wiki page

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#118]
## Description
The issue description.

## Tasks
- [x] Review the Customer Milestone 1 Report content.
- [x] Create the wiki page for the report.
- [x] Add introduction, and team members' names
- [x] Add table of content and headings of the sub-sections.

## Estimated Time
25 mins.

## Deadline
Date(22/04/2024) - 23.59

## Reviewer
@set120120  - Deadline of the review(24/04/2024 - 23.59)

**Comment by ebrarkiziloglu** [comment]
It took me 25 minutes to initiate the milestone report [wiki page](https://github.com/bounswe/bounswe2024group5/wiki/Customer-Milestone-2-Report).
The issue is read to be reviewed.

**Comment by set120120** [comment]
Looks nice for me. Good job @ebrarkiziloglu
