### ISSUE TITLE
Dockerize the application

### ISSUE THREAD

**Issue by HutkuC** [bounswe/bounswe2024group5#125]
## Description
We need to dockerize our application to make deployment safe and easier. We need two Dockerfiles for backend, and frontend. We do not need to write a Dockerfile for database, we can use the [mysql](https://hub.docker.com/_/mysql) image for that. We might need a second docker-compose file for development environment, but not yet decided.

## Tasks
- [x] Create Dockerfile for backend
- [x] Create Dockerfile for frontend
- [x] Create docker-compose.yml for deployment.
- [x] Test the database deployed by docker-compose.

## Estimated Time
300

## Deadline
26/04/2024 - 23:59

## Reviewer
@odenizddd - Deadline of the review(27/04/2024 - 23:59)
