### ISSUE TITLE
Implement Mobile for MVP

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#126]
## Description
The registration and login pages for mobile should be implemented.

## Tasks
- [x] #133
- [x] Implement login and register screens - @ramazanoacar 
- [x] #136
- [x] ~Implement profile settings page - @arincdemir~
- [x] Explore bottom tab layout for the mobile application - @ramazanoacar 
- [x] #135
- [x] #134
- [x] #152
- [x] #153
- [x] #154

## Estimated Time
600 mins.

## Deadline
Date(27/04/2024) - 23.59

## Reviewer
@HutkuC - Deadline of the review(28/04/2024 - 23.59)

**Comment by ramazanoacar** [comment]
I marked as done some of the subtasks of mine that we went over when we meet

**Comment by ebrarkiziloglu** [comment]
Implementing the personal profile settings page is postponed for the next milestone.
