### ISSUE TITLE
Write the Customer Milestone Report 2

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#140]
## Description
@ebrarkiziloglu initiated the [report](https://github.com/bounswe/bounswe2024group5/wiki/Customer-Milestone-2-Report) previously. We need to fill in the subsections. 

## Tasks
- [x] Write the  `1.1 Project Summary` section in the milestone report. @ebrarkiziloglu 
- [x] Write the  `1.2 Project Status` section in the milestone report. @ebrarkiziloglu 
- [x] Write the  `1.3 Our Code` section in the milestone report. @odenizddd 
- [x] Write the  `1.4 The Deployed Application` section in the milestone report. @HutkuC 
- [x] Write the  `1.5.1 Class Diagram` section in the milestone report. @ebrarkiziloglu 
- [x] Write the  `1.5.2 Use-Case Diagram` section in the milestone report. @ebrarkiziloglu 
- [x] Write the  `1.5.3 Sequence Diagrams` section in the milestone report. @ebrarkiziloglu 
- [x] Write the  `1.6 Updated Project Plan` section in the milestone report. @ebrarkiziloglu 
- [x] Write the  `1.7 Implementation Specific Meeting Notes` section in the milestone report. @ebrarkiziloglu 
- [x] Write the  `1.8 Lessons We Learned` section in the milestone report. @HutkuC @arincdemir @Ultiminati 
- [x] Write the  `1.9 Our Team Management Process` section in the milestone report. @ebrarkiziloglu 
- [x] Write the `1.10 Challenges We Addressed` section in the milestone report. @HutkuC @arincdemir @odenizddd 
- [x] Everyone add their contribution sub-section to the  `2 Individual Contributions` section in the milestone report.

## Estimated Time
--

## Deadline
Date(02/05/2024) - 23.59

## Reviewer
@Reviewer - Deadline of the review(03/05/2024 - 23.59)

**Comment by ebrarkiziloglu** [comment]
I wrote the sections  1.1, 1.2, 1.5, 1.6, 1.7, and 1.9. I also contributed to 1.8 and 1.10 in terms of mobile implementation. I also wrote my personal contribution

**Comment by ebrarkiziloglu** [comment]
We worked collectively to finalize the [milestone report](https://github.com/bounswe/bounswe2024group5/wiki/Customer-Milestone-2-Report). Great work everyone! Closing the issue now.
