### ISSUE TITLE
Initialize backend and database

### ISSUE THREAD

**Issue by HutkuC** [bounswe/bounswe2024group5#141]
## Tasks
- [x] Initialize the backend. It should be run by docker-compose
- [x] Initialize the database. Tables should be created on fresh-start.
- [x] Test the database connection of the backend.

## Estimated Time
10 hours.

## Deadline
26/04/2024

**Comment by HutkuC** [comment]
This issue is created to log work done. Tasks are already finished and merged to main branch.
