### ISSUE TITLE
Fix minor bugs in mobile

### ISSUE THREAD

**Issue by ramazanoacar** [bounswe/bounswe2024group5#158]
## Description
Fix some issues before final version

## Tasks
- [x] Navigate share a post screen to CreatePost screen
- [x] Make magnifying glass in the search bar a clickable button
- [ ] Handle network error in apk (potentially caused from json.parse())
- [x] #161
- [x] Go over issue of lowercase username in textInput in Login and Register
- [x] #159 [@ramazanoacar ]
- [x] #160 [@ramazanoacar ] CANCELLED
- [x] change regex for password requirement

## Estimated Time
360 minutes

## Deadline
Date(30/04/2024) - 20.00

## Reviewer
@HutkuC  - Deadline of the review(30/04/2024 - 21.00)

**Comment by ramazanoacar** [comment]
@arincdemir @ebrarkiziloglu @HutkuC since the network error subissue is not so "minor" and we still couldn't handle, I suggest we close this issue with aborting it and create a new issue just for this spesific network error?

**Comment by ebrarkiziloglu** [comment]
Agreed! Let's plan to work on this together ASAP!
