### ISSUE TITLE
Implement authentication endpoints

### ISSUE THREAD

**Issue by HutkuC** [bounswe/bounswe2024group5#163]
## Description
Using JWT, a token based authentication should be implemented and tested.

## Tasks
- [x] Implement register endpoint
- [X] Implement login endpoint
- [X] Test tokens generated by backend

## Estimated Time
6h

## Deadline
Date(30/04/2024) - 08.00

## Reviewer
@set120120 Deadline of the review(30/04/2024 - 09.00)
