### ISSUE TITLE
Deploy application on Google Cloud

### ISSUE THREAD

**Issue by HutkuC** [bounswe/bounswe2024group5#164]
## Description
Backend, frontend and database should be running in remote server and accessible from outside.

## Tasks
- [x] Fix ip addresses in frontend.
- [x] Create VM instance in Google Cloud Console and make configurations.
- [x] Deploy the application.

## Estimated Time
3h

## Deadline
Date(30/04/2024) - 08.30

## Reviewer
@set120120  - Deadline of the review(30/04/2023 - 09.30)

**Comment by set120120** [comment]
Everything was excellent. We use deployment in google services you did in demo session. Thank you so much. @HutkuC
