### ISSUE TITLE
Implement For you Page and Post component - mobile - @ebrarkiziloglu 

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#200]
## Description
A feed page (or a for you page) needs to be implemented for mobile. An empty feed page is already available.

## Tasks
- [x] Implement a Post component to display in the Feed Page.
- [x] Handle like count for posts.
- [x] Handle commenting for posts [require a separate comment page].
- [x] Add scroll functionality to the Feed page. 

## Estimated Time
100 mins

## Deadline
Date(14/05/2024) - 23.59

## Reviewer
@ramazanoacar  - Deadline of the review(15/05/2024 - 23.59)

**Comment by ebrarkiziloglu** [comment]
I implemented the necessary parts in the [add/mobile-post](https://github.com/bounswe/bounswe2024group5/tree/add/mobile-post) branch. However, the images to be displayed for posts are currently hardcoded into the `Post.tsx`. I might need some help to make them dynamic.

**Comment by ebrarkiziloglu** [comment]
With @ramazanoacar, we were able to improve these pages. Related PR's are linked. Closing the issue now.
