### ISSUE TITLE
Implement requests to backend for all Mobile pages

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#238]
## Description
Mobile app now had a feed page, a search page, and a profile page, and create post components. We need to complete the implementations of the requests to backend endpoints.

## Tasks
- [x] Implement comment-to-a-post request in Comment screen (#215)
- [x] Implement search-query request in Search screen (#206)
- [x] Implement get-user request in Login screen (#224)
- [x] Implement like-post request in Post component and see Post screen (#232)
- [x] Implement get-user request in Personal profile screen (#232)
- [x] Implement get-user request in profile settings screen (#232)
- [x] Implement file-upload request in Create Post screen (#229)

## Estimated Time
300 mins.

## Deadline
Date(17/05/2024) - 10.00

## Reviewer
no need since the PR's will be reviewed.

**Comment by ebrarkiziloglu** [comment]
The corresponding PR's were connected to the issue.
