### ISSUE TITLE
Archive the old project.

### ISSUE THREAD

**Issue by odenizddd** [bounswe/bounswe2024group5#246]
## Description
Move the old project under the /archive folder so that we can start working on a new project.

## Tasks
- [x] Create the /archive folder.
- [x] Move the old project under /archive
- [x] Commit and create a pull request.

## Estimated Time
15 min

## Deadline
24/09/2024

**Comment by ebrarkiziloglu** [comment]
merged the branch to the main. Great work!
