### ISSUE TITLE
Issue: Requirements Gathering and Questions

### ISSUE THREAD

**Issue by fahreddinozcan** [bounswe/bounswe2024group5#264]
## Description
This issue is created to gather requirements and address key questions for our lecture project. The purpose of this issue is to:

- Collect and refine project requirements
- Address crucial questions about the project's functionality

## Tasks
- [x] Make suggestions about requirements
- [x] Find answers to various questions (listed below) to write a requirement
- [x] Find new questions about project

### Questions
- How will the wrong answers in the questions be determined?
- From which Linked Data sources will we get the meanings and translations of the words?
- How will we determine the difficulty of the words? Consider options such as:
    - Frequency
    - CEFR levels
    - Other potential methods
- What will be the frequency of showing past words?

## Estimated Time
120

## Deadline
01.10.2024 - 15.00

## Reviewer
@odenizddd - 01.10.2024 - 20.00

**Comment by set120120** [comment]
The questions here are similar to the comments Deniz made in [the previous issue](https://github.com/bounswe/bounswe2024group5/issues/263). I would like to answer the different question here.

We should adjust the frequency of showing the words in the past according to a certain percentage. We should calculate it as a certain percentage here (words shown in the past / all words to be shown). For example, if we will show 10 words to the user and the rate we set is 40%, 4 of these 10 words should be words we have shown to the user before. We can update this threshold as the project progresses so that we can reach the most optimal result.

**Comment by semihYILMAZ37** [comment]
We should also identify the relation between user-created quizes and generated ones. I believe we need to answer the following questions.
- Should there be any restrictions, such as difficulty level, when users create quizzes?
- Can user generated quizes be used to collect points?

**Comment by fahreddinozcan** [comment]
Seeing that most of these questions are answered in the comments section of issue #263, we can close this issue. Also, we stated our questions to Furkan, which is also available in the [meeting notes](https://github.com/bounswe/bounswe2024group5/wiki/Lab-Meeting-%232-%7C-01.10.2024).
