### ISSUE TITLE
Initialize the Mobile project

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#272]
## Description
As we plan our project, some Mobile pages, like Login screen, Register screen, a simple Home screen etc need to me implemented.

## Tasks
- [x] Implement a Login screen
- [x] Implement a Register screen
- [x] Implement a Home screen to connect to login and register screens

## Estimated Time
100 mins

## Deadline
Date(06/10/2024) - 23.59

## Reviewer
@ramazanoacar - Deadline of the review(08/10/2024 - 12.00)

**Comment by ramazanoacar** [comment]
Right now, I cannot open the simulator and check with it. However, I reviewed the PR and the code seemed cool to me. Since this is an initialization task, I believe this is enough for closing the issue. Thanks for your effort!
