### ISSUE TITLE
Create and format the Requirements Document

### ISSUE THREAD

**Issue by arincdemir** [bounswe/bounswe2024group5#276]
## Description
There should be a wiki page for requirements. It should be appropriately formatted.

## Tasks
- [x] Create the page
- [x] Format the page for different subsections
- [x] Add the page to the sidebar

## Estimated Time
15 mins

## Deadline
Date(05/10/2024) - 22:00

## Reviewer
@fahreddinozcan  - Deadline of the review(08/10/2024 : 22:00)

**Comment by arincdemir** [comment]
I created and formatted the file. @fahreddinozcan can you take a look when you have time? I'm not sure about making all the subsections dropdown menus.

**Comment by fahreddinozcan** [comment]
I think we can follow the [convention from CMPE352](https://github.com/bounswe/bounswe2024group5/wiki/352-Requirements). So let's not make everything dropdown, but only subsections like `1.x.x`.

Also, creating a subsection for some relevant docs and contents make sense to me. So instead of directly putting requirements in the sidebar, putting it under a subdirectory.

![image](https://github.com/user-attachments/assets/a4cf85cb-04f5-4bb8-bfae-1212c5ace5d1)

**Comment by arincdemir** [comment]
We modified it like you said.
