### ISSUE TITLE
Design mockups for the project

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#283]
## Description
We will design the mockup pages of our platform.

## Tasks
- [x] Login page mockup - web & mobile
- [x] Register page mockup - web & mobile
- [x] Generate quiz page mockup - mobile 
- [x] Generate quiz page mockup - web 
- [x] Add question mockup - mobile 
- [x] Add question mockup - web 

## Estimated Time
720 mins

## Deadline
Date(12/10/2024) - 19.00

## Reviewer
@set120120  - Deadline of the review(13/10/2024 - 20.00)

**Comment by ebrarkiziloglu** [comment]
@odenizddd and I created the login and register pages for web and mobile. 
We also created the Generate quiz and Add question pages for mobile.

**Comment by ebrarkiziloglu** [comment]
[Mockup page](https://github.com/bounswe/bounswe2024group5/wiki/451-Mock%E2%80%90ups) is added to wiki.

**Comment by ebrarkiziloglu** [comment]
Me and @odenizddd met today to continue working on the remaining mockups. We added the home page, the form pages and improved the quiz generation pages. All of the updated pages are available in [wiki](https://github.com/bounswe/bounswe2024group5/wiki/451-Mock%E2%80%90ups).

The remaining pages are:
- solve a quiz page
- ask a question in the form page
- view a discussion in the form page.

**Comment by set120120** [comment]
WOW, I am very impressed and cannot wait to start implementing this project 😆 . I will look at when you finished last 3 pages. Thank you for your effort @ebrarkiziloglu @odenizddd

**Comment by odenizddd** [comment]
Thank you @set120120 . Really happy to hear you liked our design. ☺

**Comment by ebrarkiziloglu** [comment]
Thanks for your great feedback @set120120!

**Comment by ebrarkiziloglu** [comment]
Me and @odenizddd met again today to continue working on the remaining mockups. 

We added the following pages:
- [X] solve a quiz page
- [X] ask a question in the form page
- [X] view a discussion in the form page.
- [X] solve a quiz preview page
- [X] search a word view

All of the updated pages are available in [wiki](https://github.com/bounswe/bounswe2024group5/wiki/451-Mock%E2%80%90ups). This is all for the mockup design step of our project planning. 
This issue is now ready for review, @set120120.

**Comment by odenizddd** [comment]
720 minutes!!! That's a lot of time. What are we doing with our lives? 🥲

**Comment by ebrarkiziloglu** [comment]
Hello @set120120, this is a friendly reminder for the overdue review. :)

**Comment by set120120** [comment]
Hello @ebrarkiziloglu thanks for your reminder. I had a very busy weekend and unfortunately I was not available. You send us the mockups via WhatsApp (I looked them). Everything looks cool. Maybe, we can choose colors of the application together later. I say "maybe" because it is good for me but we should ask all team. Besides these, I added the link of Deniz's page in Authors section. Now, everything is okay. Thank you both for your efforts.
