### ISSUE TITLE
Create Quiz with in-app/ mock data

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#293]
## Description
Implement a create quiz page for the mobile.

## Tasks
- [x] Add a navigation bar to the home page
- [x] Add the create quiz button that directs to the Quiz Creation page
- [x] Implement the Quiz Creation page in basic format

## Estimated Time
480 mins

## Deadline
Date(15/10/2024) - 12:00

## Reviewer
@ramazanoacar - Deadline of the review(15/10/2024 - 20:00)

**Comment by ebrarkiziloglu** [comment]
All of the above is implemented in the `293-create-quiz-with-in-app-mock-data` branch.

**Comment by ebrarkiziloglu** [comment]
I [fixed](https://github.com/bounswe/bounswe2024group5/blob/293-create-quiz-with-in-app-mock-data/mobile/Quizzard/components/DropdownComponent.tsx) the dropdown menu view. It looks more neat now, see the image below: 

![ss - add quiz 3](https://github.com/user-attachments/assets/88ade406-60e8-4d83-be45-8cd6d2c984b6)

**Comment by ebrarkiziloglu** [comment]
this took me 3.5 hours. Not a bad estimate :)
