### ISSUE TITLE
Implement Quiz Listing Page

### ISSUE THREAD

**Issue by fahreddinozcan** [bounswe/bounswe2024group5#298]
## Description
Listing quizzes is one of the major features of this application. Users need to be able to perform below tasks

## Tasks
- [x] List all quizzes
- [ ] See the quizzes' related metadata
- [ ] Filter the quizzes
- [ ] See a way to create new quizzes

## Estimated Time
6h

## Deadline
19.10.2024

## Reviewer
@odenizddd
