### ISSUE TITLE
Prepare RAM.

### ISSUE THREAD

**Issue by semihYILMAZ37** [bounswe/bounswe2024group5#302]
## Description
Responsibility assignment matrix should be created and then the work done must be added to the matrix.

## Tasks
- [x] ~Create the matrix~
- [x] ~Add meetings to the matrix~
- [x] ~Add issues to the matrix~

## Estimated Time
2h

## Deadline
Date(15/10/2024) - 17:00

## Reviewer
@set120120  - Deadline of the review Date(16/10/2024) - 17:00

**Comment by set120120** [comment]
@semihYILMAZ37 Well done. There are all work up to now. We need to keep it updated. For now, this is issue can be closed.
