### ISSUE TITLE
Design Sequence Diagrams

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#304]
## Description
We will design the relevant sequence diagrams for our project.

## Tasks
- [x] Login sequence diagram @HutkuC 
- [x] Register sequence diagram @HutkuC 
- [x] Create quiz sequence diagram @odenizddd 
- [x] #312
- [x] #305
- [x] #306
- [x] #313
- [x] Edit quiz sequence diagram @odenizddd 

## Estimated Time
Time estimation in minutes.

## Deadline
Date(18/10/2024) - 20.00

## Reviewer
@set120120 - Deadline of the review(19/10/2024 - 23.59)

**Comment by ebrarkiziloglu** [comment]
The wiki page is [initiated](https://github.com/bounswe/bounswe2024group5/wiki/451-Sequence-Diagrams).

**Comment by set120120** [comment]
I think in the 3rd diagram on the wiki page (Edit Quiz), only insertion is mentioned, however both deletion and replacement should be added there.

**Comment by set120120** [comment]
![image](https://github.com/user-attachments/assets/689f8737-fb55-4df6-a26b-cdc5555346f2) 
In this photo (SS from 5th diagram), the post screen is clicked, the viewPost request is sent, but the comment section is passed without any response. Can you explain this @ebrarkiziloglu ? I think the comment section should be passed after the post screen response is received.

**Comment by set120120** [comment]
6th diagram is so cool! @fahreddinozcan

**Comment by ebrarkiziloglu** [comment]
> In this photo (SS from 5th diagram), the post screen is clicked, the viewPost request is sent, but the comment section is passed without any response. Can you explain this @ebrarkiziloglu ? I think the comment section should be passed after the post screen response is received. The rest of this diagram is very good.

You're right, the post should be displayed before the user attempts to comment. Can you check the diagram again @set120120 ?

**Comment by ebrarkiziloglu** [comment]
Also, we had agreed on using the term 'Reply' instead of commenting, so I also fixed that for the diagram 5.

**Comment by set120120** [comment]
Now, they are okay. Good work @ebrarkiziloglu

**Comment by set120120** [comment]
I am waiting for the issue the last 2 diagrams to close the issue.

**Comment by ebrarkiziloglu** [comment]
The issue is now ready for review @set120120.

**Comment by set120120** [comment]
Everything is okay. Thanks for your effort. @ebrarkiziloglu @odenizddd @HutkuC @fahreddinozcan
