### ISSUE TITLE
Forum Page

### ISSUE THREAD

**Issue by ramazanoacar** [bounswe/bounswe2024group5#315]
## Description
Implement the Home page with the Quiz View and other missing details for the mobile.

## Tasks
- [x] Implement the Forum page view with mock data
- [x] Implement search word page, no data for right now
- [x] Implement Question Page that navigates from Forum Page, use mock data
- [x] Implement create forum question screen

## Estimated Time
120 mins

## Deadline
Date(22/10/2024) - 08:00

## Reviewer
@ebrarkiziloglu   - Deadline of the review(25/10/2024 - 10:00)

**Comment by ramazanoacar** [comment]
hello @ebrarkiziloglu can you review this issue, since we've already went over in the meetings and customer presentation.

**Comment by ebrarkiziloglu** [comment]
Sure, as I also reviewed the related PR, we can close the issue now. Thanks for your efforts!
