### ISSUE TITLE
Arrange the Project plan and review frequently

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#317]
## Description
We use Github's project's [Roadmap View](https://github.com/orgs/bounswe/projects/67/views/4) for the project planing. The Roadmap needs frequent review to add the missing issues to our Project, add the issue status and add start & end dates to the issue for the Roadmap view. 

## Tasks
- [x] Add the issues of the Milestone 1 to the Roadmap.  
- [x] Track the issues of Milestone 2 (Customer milestone 1) and add them to the roadmap.
- [x] Add future plan items to the roadmap, before the Customer milestone 1.
- [ ] Track the issues of the next Milestone. 

## Estimated Time
30 min per milestone

## Deadline
Until the end of the semester.

## Reviewer
@semihYILMAZ37

**Comment by ebrarkiziloglu** [comment]
I want to keep this issue open throughout the semester as a reminder for myself to frequently revise the project plan. This will require occasional reviews, especially before the Customer milestone submissions. At those times, I will need your review @semihYILMAZ37.

**Comment by ebrarkiziloglu** [comment]
I initiated the [Customer Milestone 2](https://github.com/bounswe/bounswe2024group5/milestone/6) and [Final milestone](https://github.com/bounswe/bounswe2024group5/milestone/7), form them to be displayed in the Project Plan Roadmap.

**Comment by ebrarkiziloglu** [comment]
I added the missing issues, and also added some entries for our **tentative** future plan for the project. 

This issue is now ready for review for this milestone @semihYILMAZ37

**Comment by semihYILMAZ37** [comment]
Thanks for your efforts Ebrar. Our project plan look cool in roadmap view.

**Comment by semihYILMAZ37** [comment]
The plan looks perfect. All of the work done until the last milestone can be seen clearly. Thanks for your efforts!

**Comment by ebrarkiziloglu** [comment]
I have added all the missing existing issues to the current Milestone and the Project.

**Comment by semihYILMAZ37** [comment]
I checked the project plan. It is cool. Thanks for your effort Ebrar!
