### ISSUE TITLE
Implement API requests for mobile

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#319]
## Description
Add API calls for mobile. The endpoints are listed below according to their priority for the Customer Presentation 1.

## Tasks
- [x] Register & Login
- [x] Create a new Quiz: Post /quizzes
- [x] Get list of Quizzes: Get /quizzes
- [ ] Get a specific Quiz: Get /quizzes/{id}
- [ ] Solve Quiz: Post /quizzes/{id}/solve
- [ ] Check the functionality of the API calls to make sure we connect to backend correctly

## Estimated Time
4 days

## Deadline
st Customer Presentation
Date(21/10/2024) - 23.59

## Reviewer
@HutkuC - Deadline of the review(21/10/2024 - 23.59)

**Comment by ebrarkiziloglu** [comment]
With @ramazanoacar's valuable contributions, we finished the implementations of the authentication and GET /quizzes api requests for the Customer Milestone 1. This issue is closed, and we will continue developing the rest of the api calls in the future.
