### ISSUE TITLE
Write the Customer Milestone 1 Report

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#320]
## Description
We need to write a milestone report to submit. The instructions for the report is in [moodle](https://moodle.bogazici.edu.tr/pluginfile.php/1721368/mod_resource/content/1/First%20Customer%20Presentation%20Deliverables.pdf).

## Tasks
- [x] Initiate the wiki page and add the intro and table of content sections. - @ebrarkiziloglu 
- [x] 1. Executive Summary - @odenizddd 
- [x] 2. Customer Feedback and Reflections - @odenizddd 
- [x] 3. List and Status of Deliverables - @ebrarkiziloglu 
- [x] 3.1 Evaluation of the status of Deliverables [ and its impact on your project plan (reflection) ] - @ebrarkiziloglu 
- [x] 3.2 Adressed Requirements - @semihYILMAZ37 
- [x] 4. Evaluation of Tools - @odenizddd 
- [x] 6. Deliverables - @semihYILMAZ37 
- [x] #326

## Estimated Time
3 days

## Deadline
Date(25.10.2024) - 12.00

## Reviewer
@set120120 - Deadline of the review(25.10.2024 - 17.00)

**Comment by ebrarkiziloglu** [comment]
I initiated the [wiki page](https://github.com/bounswe/bounswe2024group5/wiki/451-Customer-Milestone-1-Report), added the Intro section, other section titles, related table of content.

**Comment by ebrarkiziloglu** [comment]
I finished my sections, and also reviewed @odenizddd's work. I love the Customer Feedback reflection section! Thanks for your efforts.  

@semihYILMAZ37, @ramazanoacar would you like to finish the 2 remaining sections?

**Comment by ramazanoacar** [comment]
I am sorry but I won't have time for this one, especially these days are not okey for me.

**Comment by semihYILMAZ37** [comment]
Closing this issue since #343 has already reviewed by @set120120 and merged.
