### ISSUE TITLE
Create Issue Template

### ISSUE THREAD

**Issue by SouthAscend** [bounswe/bounswe2024group5#34]
## Description
The issue template we are using is a wiki page, it needs to be recreated as a real issue template.

## Tasks
- [X] ~Research and learn about configuration files.~
- [X] ~Write the configuration files and add it to github.~
- [X] ~Test if it works.~

## Deadline
25/02/2024 - 23,59

## Reviewer
@HutkuC  - 26/02/2024 23,59

**Comment by SouthAscend** [comment]
There should be a prompt in the "New Issue" screen now. After the research, we can make different issue templates if needed.

**Comment by SouthAscend** [comment]
I've updated the link on the wiki sidebar. I've deleted the wiki page about the issue template.

**Comment by SouthAscend** [comment]
@HutkuC The issue has needed to be reviewed for a long time.

**Comment by HutkuC** [comment]
LGTM
