### ISSUE TITLE
Implement Quiz Attempts Backend

### ISSUE THREAD

**Issue by semihYILMAZ37** [bounswe/bounswe2024group5#356]
## Description
Each quiz attempt by users must be kept in the database. We need to implement related endpoints for that purpose. The implementation must support partial attempts.

## Tasks
- [x] Add/Update related database table.
- [x] Add related model and repository classes.
- [x] Add related service class.
- [x] Implement POST requests.
- [x] Implement GET requests.
- [x] Implement PUT requests.
- [x] Implement DELETE requests.
- [x] Update API documentation.

## Estimated Time
4 hours

## Deadline
Date(16/11/2024) - 23:59

## Reviewer
@set120120  - Deadline of the review(17/11/2024 - 23:59)

**Comment by set120120** [comment]
This issue was closed because PR was checked.
