### ISSUE TITLE
Implement Question Answers Backend

### ISSUE THREAD

**Issue by semihYILMAZ37** [bounswe/bounswe2024group5#358]
## Description
We need to implement backend endpoints to handle answering quiz questions.

## Tasks
- [x] Implement POST requests.
- [x] Implement GET requests.
- [x] Implement PUT requests.
- [x] Implement DELETE requests.
- [x] Update API documentation.

## Estimated Time
5 hours

## Deadline
Date(17/11/2024) - 23:59

## Reviewer
@HutkuC  - Deadline of the review(19/11/2024 - 17:00)
