### ISSUE TITLE
Update older issue's - Güney

### ISSUE THREAD

**Issue by SouthAscend** [bounswe/bounswe2024group5#36]
## Description
Update the old issues according to the current issue template

## Tasks
- [x] ~Update the issue [#1](https://github.com/bounswe/bounswe2024group5/issues/1)~
- [x] ~Update the issue [#20](https://github.com/bounswe/bounswe2024group5/issues/20)~
- [x] ~Update the issue [#21](https://github.com/bounswe/bounswe2024group5/issues/21)~

## Deadline
25/02/2024 - 23.59

## Reviewer
@arincdemir - 26/02/2024 - 23.59

**Comment by SouthAscend** [comment]
I have updated the issues with the current template.

**Comment by arincdemir** [comment]
I see that you have updated the old issues that you were assigned to.
