### ISSUE TITLE
Implement delete and edit buttons for user's created quizzes for Mobile

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#367]
## Description
Users shall be able to access the quizzes they created from their personal pages, and delete them. 

## Tasks
- [x]  Use the existing QuizViewComponent in profile page.
- [x]  Add delete and edit buttons to the QuizViewComponent.
- [x]  Add the backend connection for delete button.

## Estimated Time
100 mins.

## Deadline
Date(18/11/2024) - 20.00

## Reviewer
@arincdemir - Deadline of the review(19/11/2024 - 23.59)

**Comment by ebrarkiziloglu** [comment]
I implemented these features. The edit button is not connected to backend yet.
