### ISSUE TITLE
Implement Forum Post Backend

### ISSUE THREAD

**Issue by semihYILMAZ37** [bounswe/bounswe2024group5#369]
## Description
We need to implement backend endpoints to handle forum posts.

## Tasks
- [x] Implement POST requests.
- [x] Implement GET requests.
- [x] Implement PUT requests.
- [x] Implement DELETE requests.
- [x] Update API documentation.

## Estimated Time
3 hours

## Deadline
Date(19/11/2024) - 23:59

## Reviewer
@set120120   - Deadline of the review(20/11/2024 - 23:59)
