### ISSUE TITLE
Implement Difficulty Level of the Program

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#372]
## Description
In our application, the score will be calculated according to a certain use of words. According to this score, the average score of the quizzes and the User's score should be calculated. The User's score will be evaluated according to the correct or incorrect status of the quizzes he/she solved. For this, a simple scoring system will be created at first and then detailed.

## Tasks
- [x] Create a SQL file that writes words in CSV into the our database
- [x] Find an algorithm to calculate a point for words
- [x] Find CEFR equivalents according to points 
- [x] Find an algorithm to calculate points of quizAttemps 
- [x] Modify some services in backend to be able to update users' point

## Estimated Time
660 mins

## Deadline
19.11.2024 (23.59)

## Reviewer
@semihYILMAZ37 - Deadline of the review(20.11.2024 - 23.59)
