### ISSUE TITLE
Integrate WordNet Data and Scoring into Database

### ISSUE THREAD

**Issue by HutkuC** [bounswe/bounswe2024group5#383]
## Description
Fetch word meanings from WordNet, organize them, and write the data into the database. Additionally, store the scores of words in the "english" table.

## Tasks
- [x] Research and finalize the method for extracting word meanings from WordNet.
- [x] Develop a script to fetch and organize word meanings from WordNet.
- [x] Write the organized data and scores into the database.
- [x] Test migration scripts

## Estimated Time
24 hours

## Deadline
23/11/2024 - 00:00

## Reviewer
@set120120  - Deadline of the review(23/11/2024 - 12:00)
