### ISSUE TITLE
Implement Backend for User Profile

### ISSUE THREAD

**Issue by semihYILMAZ37** [bounswe/bounswe2024group5#384]
## Description
Backend endpoints for getting user profile and editing the profile must be implemented.

## Tasks
- [x] Implement GET requests.
- [x] Implement PUT requests.
- [x] Update API documentation.

## Estimated Time
2 hours

## Deadline
Date(23/11/2024) - 23:59

## Reviewer
@set120120  - Deadline of the review(24/11/2024 - 23:59)
