### ISSUE TITLE
Enhance Backend for Quizzes and Questions

### ISSUE THREAD

**Issue by semihYILMAZ37** [bounswe/bounswe2024group5#385]
## Description
We already have endpoints for quiz creation and retrieval. However, we cannot edit or delete quizzes. Also filters for quiz retrievals are not implemented yet. Moreover we need some endpoints to handle operations on single question instead of using quiz endpoints.

## Tasks
- [ ] Add filters for quiz retrievals.
- [ ] Implement editing quiz meta data.
- [ ] Implement adding question to quiz.
- [ ] Implement removing question from quiz.
- [ ] Impelement editing a question.
- [ ] Implement quiz deletion.

## Estimated Time
4 hours

## Deadline
Date(23/11/2024) - 23:59

## Reviewer
@HutkuC  - Deadline of the review(24/11/2024 - 23:59)
