### ISSUE TITLE
Favorite Quizzes and Questions

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#391]
## Description
In our application, users can add questions and quizzes to favorites. So, we need to implement that functionality.

## Tasks
- [x] Implement adding quizzes to favorites
- [x] Implement adding questions to favorites
- [x] ~Implement an endpoint for related quiz recommendations~ (canceled)

## Estimated Time
240 mins

## Deadline
24.11.2024 - 18.40

## Reviewer
@semihYILMAZ37  - Deadline of the review(dd/mm/yyyy - hour)
