### ISSUE TITLE
Update Forum Post Endpoints

### ISSUE THREAD

**Issue by semihYILMAZ37** [bounswe/bounswe2024group5#393]
## Description
To retrieve forum posts, upvotes, and replies we should utilize username instead of userId.

## Tasks
- [ ] update get post
- [ ] update get upvotes
- [ ] update get replies

## Estimated Time
30

## Deadline
Date(23/11/2024) - 23:59

## Reviewer
@set120120
