### ISSUE TITLE
Study the working mechanism of Git

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#40]
## Description
Follow the Git tutorials to learn about some advanced git commands.

## Tasks
- [x] Watch a tutorial on Git.
- [x] Create a local repo to practice git commands. 
- [x] Take notes of useful commands.

## Deadline
Date(27/02/2024) - 00.00 

## Reviewer
Reviewer is not needed since this is for self-learning.

**Comment by ebrarkiziloglu** [comment]
I watched several short tutorials from GitHub's [youtube channel](https://www.youtube.com/@GitHub). 

Here is a very cool Git command to visualize the commits chain:
```
git log --graph --decorate --all
```
