### ISSUE TITLE
Mobile App Fixes && Missing API calls

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#411]
## Description
The following tasks are inckuded in this issue, regarding several quiz functionalities of the mobile app.

## Tasks
- [x] Implement `file/upload` endpoint to process the images in creating quizzes. 
- [x] Create a `hostContext` variable to dynamically handle the IP address instead of hard-coding it.
- [x] Add Login via enter click.
- [x] Use the same dropdown component from the home screen for setting the English proficiency in registration. 
- [x] Fetch user data from backend to display in profile page
- [x] Fix image display in the home page
- [ ] API calls for the QuizSolvingScreen (Quiz Attempt)

## Estimated Time
480 mins

## Deadline
Date(24/11/2024) - 23.59

## Reviewer
@ramazanoacar or @arincdemir  - Deadline of the review(25/11/2024 - 20.00)
