### ISSUE TITLE
Revise Auto-complete backend

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#424]
## Description
The autocomplete function need to be revised. The Turkish version should be added.

## Tasks
- [ ] Add Turkish version
- [ ] Check function correctness
- [ ] Update api-doc

## Estimated Time
120 mins

## Deadline
25.11.2024 - 11.59

## Reviewer
@HutkuC  - 25.11.2024 - 17.59
