### ISSUE TITLE
Update the Meeting Template

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#43]
## Description
There is a need for separate outcomes and action items sections in the meeting notes, so that missing team members can read the note and catch up with all important points.

Also converting bullet points into tables, and adding some symbols / emojis will make the template more presentable and readable.

## Tasks
- [x] Add an outcomes section.
- [x] Add a table view for the action items.
- [x] Add relevant emojis and highlights. 

## Estimated Time
25 mins.

## Deadline
Date(26/02/2024) - 21.30

## Reviewer
@Ultiminati - Deadline of the review(27/02/2024 - 09.00)

**Comment by ebrarkiziloglu** [comment]
In addition to the tasks above, I also added a 'issues' column to the action items table. This we, we can keep track of the relative issues from the meeting notes.

**Comment by Ultiminati** [comment]
The tasks specified here are seen to be properly implemented.
