### ISSUE TITLE
Update the Github Research page

### ISSUE THREAD

**Issue by SouthAscend** [bounswe/bounswe2024group5#44]
## Description
The [main research page](https://github.com/bounswe/bounswe2024group5/wiki/Research-on-Everything) needs to be updated.

## Tasks
- [ ] Add a general tutarial of our repository
- [ ] Define the terms
- [ ] Define the roles

## Estimated Time
30 min

## Deadline
26/02/2024 - 20.46

## Reviewer
@set120120 - 27/02/2024 17.00

**Comment by SouthAscend** [comment]
I've updated our github page and renamed it as [Learning GitHub](https://github.com/bounswe/bounswe2024group5/wiki/Learning-Github). While reviewing, double-checking for the explanations of the terms, roles, and concepts is required.

**Comment by set120120** [comment]
Everything seems OK. Great job Güney!
