### ISSUE TITLE
Do the final fixes to mobile

### ISSUE THREAD

**Issue by arincdemir** [bounswe/bounswe2024group5#450]
## Description
The following points need fixing:

## Tasks
- [x] splash image and icon
- [x] home screen not taking user elo from api
- [x] home screen not getting difficulty from api
- [x] bug in quizzes for you filtering
- [x] quiz not finishing properly
- [x] false answer not showing red when you return back to previous questions
- [x] quiz attempt not showing already picked answers when you return back

## Estimated Time
120 mins

## Deadline
Date(25/11/2024) - 22:00
