### ISSUE TITLE
Write the Customer Milestone 2 Report

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#459]
## Description
We need to write a milestone report to submit. The instructions for the report is in [moodle](https://moodle.bogazici.edu.tr/pluginfile.php/1734206/mod_resource/content/3/Second%20Customer%20Presentation%20Deliverables.pdf).

## Tasks
- [x] Initiate the wiki page and add the intro and table of content sections. - @ebrarkiziloglu 
- [x] 1. Executive Summary - @ebrarkiziloglu 
- [x] 2. Customer Feedback and Reflections - @ramazanoacar 
- [x] 3. List and Status of Deliverables - @ebrarkiziloglu 
- [x] 3.1 Evaluation of the status of Deliverables - !!only API documentation section!! - 
- [x] 3.2 Requirements Adressed In this milestone - @ebrarkiziloglu 
- [x] 3.3 Evaluation of tools managing the project - @ebrarkiziloglu 
- [x] 4.1. Change of plans since Milestone 1 - 
- [x] 4.2. Plan for completing the project - @fahreddinozcan 
- [x] 4.3 Project plan, link to it, screenshots etc - @ebrarkiziloglu 
- [x] 6. Deliverables simle sections with links - @ebrarkiziloglu 
- [x] 6.4 UX Design with focus on domain-specific nature of the features - @fahreddinozcan 
- [x] 6.5 Description of the standard being utilized (with examples) -  @odenizddd 
- [x] 6.6 API Documentation with examples - @set120120 
- [x] 7.1. General Testing Plan for the project - @fahreddinozcan 
- [x] 7.2.1 Generated unit test report - back - @set120120 
- [x] 7.2.2 Generated unit test report - front - @fahreddinozcan 
- [x] 7.2.3 Generated unit test report - mobile - @ramazanoacar 
- [x] Individual contributions #460 
## Estimated Time
20 hours

## Deadline
Date(29/11/2024) - 20.00

## Reviewer
No need.

**Comment by ebrarkiziloglu** [comment]
I initiated the report [wiki](https://github.com/bounswe/bounswe2024group5/wiki/451-Customer-Milestone-2-Report).

**Comment by fahreddinozcan** [comment]
I created the [unit test report for frontend](https://github.com/bounswe/bounswe2024group5/wiki/451-Customer-Milestone-2-Report#722-frontend)

**Comment by set120120** [comment]
I created the unit test report for backend

**Comment by ramazanoacar** [comment]
I added test report for mobile and customer feedback & reflections

**Comment by ebrarkiziloglu** [comment]
Great job team! 🤩
