### ISSUE TITLE
Implement Endpoints for Following Functionality

### ISSUE THREAD

**Issue by semihYILMAZ37** [bounswe/bounswe2024group5#471]
## Description
Users will be able to follow each other thanks to these endpoints.

## Tasks
- [ ] add necessary table to the database creation script.
- [ ] implement the endpoints.
- [ ] update the API doc.

## Estimated Time
3 hours

## Deadline
Date(09/12/2024) - 22:00

## Reviewer
@set120120  - Deadline of the review(10/12/2024) - 22:00
