### ISSUE TITLE
Add profile page and quiz creation tests for mobile

### ISSUE THREAD

**Issue by ramazanoacar** [bounswe/bounswe2024group5#473]
## Description
Integration and unit tests for profile page and quiz creation should be added. Existing parts should be fixed.

## Tasks
- [x] Integration test for profile 
- [x] Integration test for quiz creation 
- [x] Unit test for profile
- [x] Unit test for quiz creation 

## Estimated Time
180 minutes

## Deadline
Date(15/12/2024) - 12.00

## Reviewer
@set120120  - Deadline of the review(16/12/2024 - 23.59)

**Comment by ramazanoacar** [comment]
Even though the tests don't perform well, I implemented them and tried to cover general functionalities. Cacn you review the issue, please @set120120

**Comment by set120120** [comment]
@ramazanoacar thanks for your effort. This issue can be closed now.
