### ISSUE TITLE
Fix Quiz attempt API call and add missin API calls for this screen

### ISSUE THREAD

**Issue by ramazanoacar** [bounswe/bounswe2024group5#475]
## Description
Issues in the api calls of submitting answer should be fixed and some unimplemented api calls should be handled.

## Tasks
- [x] Fix submitting answer
- [x] Fix quiz attempt submission if it still persists after the above task
- [x] Add remainder of the api calls (ie. continuing the quiz after quitting without submittin)

## Estimated Time
120 minutes

## Deadline
Date(16/12/2024) - 12.00

## Reviewer
@ebrarkiziloglu  - Deadline of the review(17/12/2024 - 12.00)

**Comment by ramazanoacar** [comment]
These are PR's including this issue:

https://github.com/bounswe/bounswe2024group5/pull/472
https://github.com/bounswe/bounswe2024group5/pull/507

**Comment by ebrarkiziloglu** [comment]
LGTM!! 💯
