### ISSUE TITLE
Implement "related posts" feature in viewing a forum post

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#485]
## Description
The issue description.

## Tasks
- [x] Related Posts button in forum post
- [x] Related Posts API connection
- [x] Related Posts UI

## Estimated Time
120 mins

## Deadline
Date(14/12/2024) - 23.59

## Reviewer
@ramazanoacar - Deadline of the review(15/12/2024 - 23.59)
