### ISSUE TITLE
Complete Profile Page 

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#488]
## Tasks
- [x] Improve the profile details
- [x] Fetch created quizzes
- [x] Fetch solved quizzes (attempts)
- [x] Fetch created forum posts
- [x] Add related navigation links from the sections of Profile Page to corresponding pages

## Estimated Time
240 mins

## Deadline
Date(14/12/2024) - 23.59

## Reviewer
@ramazanoacar - Deadline of the review(15/12/2024 - 23.59)

**Comment by ebrarkiziloglu** [comment]
Implementing the profile screen in the `488-mobile-profile-page` branch

**Comment by ebrarkiziloglu** [comment]
I greatly underestimated the effort needed for this task, as it took me more than 5 hours to fix and implement all sections of the Profile Page.
