### ISSUE TITLE
Other User's Profile Screen in Mobile

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#509]
## Tasks
- [x] Implement the other user's profile screen
- [x] Navigate to the profile screen from Forum screens
- [x] Navigate to the profile screen from Quiz screens
- [x] Navigate to the profile screen from Leaderboard & Related posts (?)
- [x] Implement the following logic
- [x] Display the follower numbers in both Profile Screens

## Estimated Time
240 mins

## Deadline
Date(14/12/2024) - 23.59

## Reviewer
@arincdemir - Deadline of the review(15/12/2024 - 23.59)

**Comment by ebrarkiziloglu** [comment]
I initiated the profile screen for others as well as navigation from forum and quiz screens. 

@ramazanoacar enhanced the profile screen by merging other users's profiles and user's own profile. He also added the follow button. 

Then I implemented the additional following/follower pages and implemented the necessary navigations between pages.

**Comment by ebrarkiziloglu** [comment]
With all related PRs linked, I am closing the issue now. Good work!!

**Comment by ramazanoacar** [comment]
https://github.com/bounswe/bounswe2024group5/pull/574

I forgot to add, profile navigation from leaderboard is handled in the above PR.
