### ISSUE TITLE
Add the items from the sidebar to the Wiki Home page

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#51]
## Description
The Wiki Home page is currently mostly empty. The items from the sidebar, as well as a short introduction section will be added.

## Tasks
- [x] Add an intro section.
- [x] Add the team members and links to their personal wiki pages.
- [x] Add the most recent five meeting notes. 
- [x] Add the templates and research pages. 

## Estimated Time
30 mins

## Deadline
Date(26/02/2024) - 23.00

## Reviewer
@odenizddd  - Deadline of the review(27/02/2024 - 09.00)

**Comment by ebrarkiziloglu** [comment]
Filled the Wiki home page. 
Took about 20 mins.

**Comment by ebrarkiziloglu** [comment]
This issue needs review now @odenizddd.

**Comment by odenizddd** [comment]
Looks good. I didn't realize I was the reviewer. Sorry for the delay.
