### ISSUE TITLE
Implement related quizzes endpoint

### ISSUE THREAD

**Issue by semihYILMAZ37** [bounswe/bounswe2024group5#519]
## Description
Given a quizId, we should return new quiz suggestions for the user requested. Please note that it is better to suggest those which user has not solve before.

## Tasks
- [x] Find quizzes according to their difficulty levels.
- [x] Eliminate those the user solved before. 
- [x] Document the API

## Estimated Time
1 hour

## Deadline
Date(13/12/2024) - 22:00

## Reviewer
@set120120  - Deadline of the review(14/12/2024) - 22:00
