### ISSUE TITLE
Do Research on API's - Ebrar Kiziloglu

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#57]
## Description
From the Professor's notes to us: There is a need for some research related to our upcoming project, in terms of domain analysis.

## Tasks
- [x] Explore Wikidata, Linked Data, SPARQL semantic queries.
- [ ] Learn and experiment with Wikidata API. [Put specific queries and responses in your Wiki under "research".]
- [ ] Research for mobile application development.
- [ ] Research for web application development
- [x] #62 

## Estimated Time
180 mins.

## Deadline
Date(05/03/2024) - 09.00

## Reviewer
No reviewer needed since this is a learning task.
