### ISSUE TITLE
Do research on Data Analysis and Take Notes 

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#58]
## Description
The professors [recommends](https://moodle.bogazici.edu.tr/mod/forum/discuss.php?d=146623) us to make a domain analysis on the following topics:
- Wikidata, Linked Data, SPARQL semantic queries, Wikidata API.

## Tasks
- [x] Learn about Wikidata, Linked Data, SPARQL semantic queries, Wikidata API.
- [x] Experiment with it.
- [x] Put specific queries and responses in your Wiki under "research".
- [x] Take some summary notes.
- [x] Provide resources for your teammates on this topic. 

## Estimated Time
60 mins.

## Deadline
Date(05/03/2024) - 10.00

## Reviewer
@arincdemir - Deadline of the review(06/03/2024 - 10.00)

**Comment by ramazanoacar** [comment]
I created the page and put my notes and research. However, I am not able to finish all the tasks before deadline. @HutkuC your assistance would be valuable in experimenting part.

**Comment by ramazanoacar** [comment]
@arincdemir can you check please

**Comment by arincdemir** [comment]
I feel like the topics should be delved a bit deeper. It is hard to understand what they are without opening the referenced page for them. Also an experiment with querying would be nice.

**Comment by ramazanoacar** [comment]
working on improving the topic. However, there was a part for experimenting. Didn't you find it adequate?

**Comment by ramazanoacar** [comment]
@arincdemir its again ready for review. I enhanced the texts. However, I disagree with you in that I experimented with the api and since this is not a intro. to computer engineering course, it would be an unnecessary effort for me to experiment again with dictionary operations in python

**Comment by arincdemir** [comment]
My point was not to teach dictionary operations, but to show that the data can be parsed like its a dictionary in python. It's ok though, I guess its not that necessary.

 Good work on the texts, thanks for your effort!

**Comment by ramazanoacar** [comment]
@arincdemir Sorry, I didn't want to say you were trying to teach dictionary operations. My intention wasn't that.
