### ISSUE TITLE
Do research on Mobile Application Development and Take Notes

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#59]
## Description
The professors [recommends](https://moodle.bogazici.edu.tr/mod/forum/discuss.php?d=146623) us to make a domain analysis on the mobile application development.

## Tasks
- [x] Learn about mobile application development.
- [x] Take some summary notes.
- [x] Provide resources for your teammates on this topic. 

## Estimated Time
60 mins.

## Deadline
Date(05/03/2024) - 10.00

## Reviewer
@ebrarkiziloglu  - Deadline of the review(06/03/2024 - 10.00)

**Comment by arincdemir** [comment]
Wrote the general overwiev; however, we should mention the tools used in front end and back end development, and mention native, hybrid, cross-platform tools.

**Comment by odenizddd** [comment]
Explained native, cross-platform, and hybrid app developments and also mentioned popular mobile development tools.

**Comment by ebrarkiziloglu** [comment]
The related research [page](https://github.com/bounswe/bounswe2024group5/wiki/Mobile-Application-Development) was generated. Thank you Arınç and Deniz.
