### ISSUE TITLE
Prepare the Final Milestone Report 

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#605]
## Description
Final milestone report will be written.

## Tasks
- [x] 1.2 Project Status - @ebrarkiziloglu 
- [x] 1.3 Final Release Notes - @ebrarkiziloglu 
- [x] 1.4 Changes Made Since Last Milestone - @ebrarkiziloglu 
- [x] 1.5 Reflections on our Final Milestone Demo - @ebrarkiziloglu 
- [x] 1.6 Reflections on our Development Process - @ebrarkiziloglu 
- [x] 1.7 Known Issues - @ebrarkiziloglu 
- [x] 2.2 Status of Requirements - @ebrarkiziloglu 
- [x] 2.3 API Endpoints: @semihYILMAZ37 
- [x] #616
- [x] 2.5 Standards
- [x] 2.6 Scenarios - @ebrarkiziloglu 
- [x] #614
- [x] #615
- [x] 4.3 Software requirements spefication (just links)
- [x] 4.4 Software design documents (just links) - @ebrarkiziloglu 
- [x] 4.5 User scenarios and mockups (just links) - @ebrarkiziloglu 
- [x] 4.6 Project plan (short intro and links) - @ebrarkiziloglu 
- [x] 4.7.1 Unit Tests - mobile: @ramazanoacar 
- [x] 4.7.2 Unit Tests - frontend: 
- [x] 4.7.3 Unit Tests - backend: @semihYILMAZ37 
- [ ] #606
- [ ] #607
- [x] Update the requirements' status (✅  / ⚠️  /  ❌ ) - @ebrarkiziloglu 
- [x] Update the UML diagrams based on the feedback we received. - @set120120 #613. 

## Estimated Time
2 hours per member.

## Deadline
Date(20/12/2024) - 18.00

## Reviewer
@everyone - Deadline of the review(20/12/2024- 22.00)

**Comment by ebrarkiziloglu** [comment]
I initiated the report [wiki page](https://github.com/bounswe/bounswe2024group5/wiki/451-Customer-Milestone-3-Report).

**Comment by ebrarkiziloglu** [comment]
I added missing requirements regarding the UI-specific points, as well as editing and deleting requirements, as we received the feedback from the TA. I also added the requirement status in the 2.2 section of the report. 

The status of the non-functional requirements have to be double checked by the backend team.

**Comment by ramazanoacar** [comment]
I added the mobile unit tests
