### ISSUE TITLE
Do research on API and Take Notes

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#61]
## Description
The professors [recommends](https://moodle.bogazici.edu.tr/mod/forum/discuss.php?d=146623) us to make a domain analysis on the Application Programming Interface (API) use and development

## Tasks
- [x] Learn about Application Programming Interface (API) use and development.
- [x] Take some summary notes.
- [x] Provide resources for your teammates on this topic. 

## Estimated Time
60 mins.

## Deadline
Date(05/03/2024) - 10.00

## Reviewer
@SouthAscend - Deadline of the review(06/03/2024 - 10.00)

**Comment by semihYILMAZ37** [comment]
I researched the topic and shared [my notes](https://github.com/bounswe/bounswe2024group5/wiki/API-Development).

**Comment by SouthAscend** [comment]
[The page](https://github.com/bounswe/bounswe2024group5/wiki/API-Development) was informative, well written, and organized.
