### ISSUE TITLE
Plan for the final presentation scenario

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#612]
## Description
We need an elaborate scenario for the final presentation.

## Tasks
- [x] Determine the features to be shown.
- [x] Plan the initial draft of the scenario. 
- [x] Finalize the scenario and rehearse it.

## Estimated Time
300 mins.

## Deadline
Date(17/12/2024) - 10.00

## Reviewer
@whole team.

**Comment by ebrarkiziloglu** [comment]
@odenizddd and I initiated the scenario during lab 9. See the [discussion](https://github.com/bounswe/bounswe2024group5/wiki/Lab-Report-9#-discussion).

**Comment by ebrarkiziloglu** [comment]
We held a meeting, with @odenizddd,  to finalize the scenario outline on December 16th, and wrote the step-by-step scenario outline. You can view the related [wiki page](https://github.com/bounswe/bounswe2024group5/wiki/Teacher-%E2%80%90-Student-Scenario-%5BCustomer-Milestone-3%5D).
