### ISSUE TITLE
Edit diagrams based on feedback

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#613]
## Description
The assistant gave us a detailed feedback after ms1. We did not have enough time during ms2. So, we need to fix the diagrams now. 😄 

## Tasks
- [x] Fix Use Case Diagram
- [x] Fix Class Diagram
- [x] Fix Sequence Diagrams

## Estimated Time
60 mins

## Deadline
20.12.2024 - 02.00

## Reviewer
@ebrarkiziloglu

**Comment by set120120** [comment]
I edited use case diagram as follows:
- Backend removed
- Different boxes but in the same usage like "Change title", "Change picture" etc collected in one box
- A box with error case removed.

**Comment by set120120** [comment]
I edited class diagram as follows:

- Created WikiDataInfo class because Wikidata said there is no such class and connected it with Question
- Added getRecommendedQuizzes to User class
- Added createQuizFromFavorites to User class
- Added follow/unfollow to User class
- Added getFollowers to User class
- Added getFollowing to User class
- Added getAverageScore to Quiz class
- Added getMostMissedQuestions to Quiz class
- Added getSuccessRateByQuestion to Quiz class
- Added getAllHints to Question class
- Added submitAnswer to QuizAttempt class
- Added editPost/deletePost to ForumPost class
- Added upvote/downvote/getVoteCount to ForumPost class
- Added upvote/downvote/getVoteCount to Reply class.

**Comment by set120120** [comment]
I've edited 1st, 3rd, 4th, 7th and 8th sequence diagrams.

**Comment by set120120** [comment]
@ebrarkiziloglu everything is ready to your review

**Comment by ebrarkiziloglu** [comment]
The changes you made definitely improved our diagrams, thanks @set120120 !

Could you also update the screenshot of the use-case diagram in its wiki page?

**Comment by set120120** [comment]
I changed the photo of the diagram in related wiki page.

**Comment by ebrarkiziloglu** [comment]
LGTM and Great Work!!
