### ISSUE TITLE
Determine System Requirements for the 'posting' subcategory.

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#73]
### Issue Description

In the planning phase of the project, we are expected to determine the requirements specification.

### Tasks

- [x] Determine requirements for posting.
- [x] Write them in the requirements page.
- [x] Determine questions to ask to the clients in terms of posting.

### Estimated Time

70

### Deadline

09/03/2024 - 23.59

### Reviewer

@set120120 - 10/03/2024 - 23.59

**Comment by ebrarkiziloglu** [comment]
I initiated the requirements [wikipage](https://github.com/bounswe/bounswe2024group5/wiki/Requirements).

**Comment by ebrarkiziloglu** [comment]
I added posting requirements to the relative [wikipage](https://github.com/bounswe/bounswe2024group5/wiki/Requirements). 
I also added my questions in terms of requirements in the [discussion page](https://github.com/bounswe/bounswe2024group5/discussions/72#discussioncomment-8736052).

The issue is ready to be reviewed @set120120.

**Comment by set120120** [comment]
I checked everything. All seems okay. Good job, Ebrar.
