### ISSUE TITLE
Issue: Add your image to team members section of readme

### ISSUE THREAD

**Issue by Ultiminati** [bounswe/bounswe2024group5#75]
### Issue Description

Either upload a photo of your choice to [here](https://github.com/bounswe/bounswe2024group5/blob/main/.github/images/members/) or link to any of your photos by editing the readme file.

Notice that the image should be square!
(While you are at it, you can upload one to your wiki page as well)

### Tasks

- [x] Abdullah Umut Hamzaoğulları
- [x] Arınç Demir
- [x] Asude Ebrar Kızıloğlu
- [x] Güney Yüksel
- [x] Halil Utku Çelik
- [x] Özgür Deniz Demir
- [x] Ramazan Onur Acar
- [x] Semih Yılmaz
- [x] Süleyman Emir Taşan

### Estimated Time

5

### Deadline

14/03/2024

### Reviewer

@Ultiminati - Deadline of the review (16/03/2024 - 23.00)

**Comment by ebrarkiziloglu** [comment]
Hey friends! 
Let's finalize our README before the submission of the first milestone. 
Our repository is one of the deliverables for the milestone. 
@SouthAscend
@semihYILMAZ37
@HutkuC

**Comment by Ultiminati** [comment]
Waiting to close the issue when completed.

**Comment by Ultiminati** [comment]
@semihYILMAZ37 after you upload your profile photo, I can close the issue.

**Comment by Ultiminati** [comment]
The profile pictures are complete, next thing to do would be to make them appear exactly same size, which is not worthy of an issue by itself. Closing the issue now.

**Comment by Ultiminati** [comment]
I've uploaded square versions of the images that were not square. @odenizddd @arincdemir @semihYILMAZ37 @SouthAscend, you can change them if you want, just letting you know.

Unfortunately, I could not make the images look exactly the same width. Someone with more expertise in Markdown could help, So I'm reopening the issue.

**Comment by SouthAscend** [comment]
@Ultiminati I've adjusted that section; all images are at the exact same size now. I couldn't manage this on a 5+4 table, so I did it on a 3x3 table.

**Comment by Ultiminati** [comment]
Thank you! It looks good, closing the issue for good :)
