### ISSUE TITLE
Modify the Meeting notes according to feedback from the teaching staff [Ebrar]

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#80]
## Description
The discussions and agenda sections of the earlier meeting notes were not structured properly.
We are advised to revise the meeting notes to reflect a better-structured template.

## Tasks
- [x] Clearly define the agenda points.
- [x] Change the Outcomes section to Discussions, for better practice. 
- [x] Review the discussion topics and reword if needed.
- [x] Modify the meeting notes template accordingly. 
- [x] Apply these changes to all (4 so far) meeting notes.

## Estimated Time
50 mins.

## Deadline
Date(13/03/2024) - 23.59

## Reviewer
@set120120 - Deadline of the review(14/03/2024 - 23.59)
