### ISSUE TITLE
Write the First Milestone Report [Ebrar & Ramazan]

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#85]
## Description
We are having our first milestone on March 18th. We will deliver the requirements, mockups and other components to the project report. 

## Tasks
- [x] Add the summary of project and overall status (Ebrar)
- [x] Add a list and Status of Deliverables (Ebrar)
- [x] Check if the Requirements page to see if it is in its final version. (Ramazan)
- [x] Document the decisions we have made, such as our domain, meetings, communication plan etc.  (Ramazan)
- [x] Documents challenges we faced. (Ramazan)
- [x] #94
- [x] #91 (Ebrar)
- [x] Add the scenarios and mockups. (Ramazan)

## Estimated Time
3 hours.

## Deadline
Date(17/03/2024) - 23.59

## Reviewer
@set120120  - Deadline of the review(18/03/2024 - 18.00)

**Comment by ebrarkiziloglu** [comment]
I initiated the report [wikipage](https://github.com/bounswe/bounswe2024group5/wiki/Customer-Milestone-1-Report).

**Comment by ebrarkiziloglu** [comment]
After conducting research on the content of a milestone report, there emerged two additional sections:
* Section 5: Evaluation of Tools, 
* Section 6: Organization and Communication.

I have written the section 6. 
@ramazanoacar could you also fill the section 5?

**Comment by ebrarkiziloglu** [comment]
The report is almost complete. @set120120 could you please specifically check the hyperlinks we have to ensure all of them work as intended? They are easy to overlook.

**Comment by set120120** [comment]
I've checked all tasks except 3rd and 6th tasks in this issue. The tasks I checked seems okay to me. However, there are some team jobs like writing individual contributions, so everyone should check own parts one more again. Besides that, everything is good enough. Well done @ebrarkiziloglu and @ramazanoacar .
