### ISSUE TITLE
Write User Scenarios

### ISSUE THREAD

**Issue by SouthAscend** [bounswe/bounswe2024group5#88]
## Description
As part of the deliverables, we need detailed user scenarios underlining different cases.

## Tasks
- [ ] Add [Scenario 1 - Feed Page](https://github.com/bounswe/bounswe2024group5/wiki/Scenario-1-%E2%80%90-Feed-Page)
- [ ] Add [Scenario 2 - Searching](https://github.com/bounswe/bounswe2024group5/wiki/Scenario-2-%E2%80%90-Searching)
- [ ] Add [Scenario 3 - Posting](https://github.com/bounswe/bounswe2024group5/wiki/Scenario-3-%E2%80%90-Posting)
- [ ] Add [Scenario 4 - Following](https://github.com/bounswe/bounswe2024group5/wiki/Scenario--4-%E2%80%90-Following)
- [ ] Add [Scenario 5 - Personal Page](https://github.com/bounswe/bounswe2024group5/wiki/Scenario-5-%E2%80%90-Personal-Page)

## Estimated Time
180 min

## Deadline
17/03/2024 - 23.59

## Reviewer
@ebrarkiziloglu - 18/03/2024 17.00

**Comment by SouthAscend** [comment]
I've added the pages, they are accesible both from the original comment of this issue and the wiki home page. There are some missing requirement for me to finish the "Acceptance Criteria" parts of the pages.

**Comment by SouthAscend** [comment]
@ebrarkiziloglu Can you review the parts other than the "Acceptance Criteria" while we update the requirements accordingly?

**Comment by ebrarkiziloglu** [comment]
@SouthAscend they look fantastic! I enjoyed the images. Thank you for your effort. 
I will review the "Acceptance Criteria" sections once you're done.

**Comment by SouthAscend** [comment]
"Acceptance Criteria" part is also done. Issue is in need of a review @ebrarkiziloglu

**Comment by ebrarkiziloglu** [comment]
LGTM! 💯
Closing the issue now.
