### ISSUE TITLE
Add a Table to provide brief summary of each team members' individual contributions.

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#91]
## Description
For the Customer Milestone 1, we will prepare a table of summaries of our individual contributions. Each member should write their own contributions.

HINT from the teaching-staff:
• Poor examples: “I attended the lectures and group meetings” or “I designed project plan”.
• Good example: “Researched the Swagger API Development support tools with <X> (an- other team member) and prepared the infrastructure. The resulting API documentation can be seen at <URI> (URI of your API documentation). ”

I have initiated the [table](https://github.com/bounswe/bounswe2024group5/wiki/Customer-Milestone-1-Report#4-individual-contribution-table) in the milestone report. 

## Tasks
Write their own contribution summary to the [table](https://github.com/bounswe/bounswe2024group5/wiki/Customer-Milestone-1-Report#4-individual-contribution-table): 
- [x] ABDULLAH UMUT HAMZAOĞULLARI
- [x] ARINÇ DEMİR
- [x] ASUDE EBRAR KIZILOĞLU
- [x] GÜNEY YÜKSEL
- [x] HALİL UTKU ÇELİK
- [x] ÖZGÜR DENİZ DEMİR
- [x] RAMAZAN ONUR ACAR
- [ ] SEMİH YILMAZ
- [x] SÜLEYMAN EMİR TAŞAN

## Estimated Time
30 mins per member.

## Deadline
Date(17/03/2024) - 20.00

## Reviewer
@ebrarkiziloglu  - Deadline of the review(18/03/2024 - 01.00)

**Comment by set120120** [comment]
I've written my contributions to the table considering hints that you provided. Thanks. @ebrarkiziloglu

**Comment by ebrarkiziloglu** [comment]
@HutkuC 
@odenizddd 
@ramazanoacar 
@semihYILMAZ37

**Comment by odenizddd** [comment]
I've added my contributions as well. Sorry for the delay @ebrarkiziloglu .

**Comment by ebrarkiziloglu** [comment]
As we submitted the milestone report, I am closing this issue now.
