### ISSUE TITLE
Create Responsibility Assignment Matrix (RAM)

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#92]
## Description
Fro the Customer Milestone 1, we need to prepare a matrix of responsibility assignments according to issues that we have done. 

## Tasks
- [x] Create the RAM.
- [x] Add all issues in an appropriate form to RAM.
- [x] Check all matches for mismatching.

## Estimated Time
75 min

## Deadline
Date(06/03/2024) - 23.59

## Reviewer
@SouthAscend

**Comment by set120120** [comment]
I've initiated the RAM. In the next step, I will add all issues to RAM.

**Comment by set120120** [comment]
I've added all issues to [RAM](https://github.com/bounswe/bounswe2024group5/wiki/RAM-(Responsibility-Assignment-Matrix)). I will check for all matches. You can review while I do this @SouthAscend .

**Comment by SouthAscend** [comment]
In the meeting, we discussed adding the role "L - Lead" to the matrix so that we could distinguish the differences between two or more assignees in issues that were assigned to multiple contributors. It's not a must-have, but it would be nice if you could add it while you are checking for matches.

**Comment by set120120** [comment]
I've completed my check. I also added "L-Lead" to the matrix to distinguish the difference between participants in the same issue. You can review now. @SouthAscend

**Comment by SouthAscend** [comment]
Everything seems great.
