### ISSUE TITLE
Provide the project plan. (Ebrar)

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#94]
## Description
For the project plan, we decided to use Github's [Roadmap view](https://github.com/orgs/bounswe/projects/52/views/4). In order to have the display, everyone needs to update their all previous issues by adding them to the Project and to the Milestone 1, and by adding start and end date so that the issues will show on the view. 

## Tasks
Update all of your issues accordingly:
- [x] ABDULLAH UMUT HAMZAOĞULLARI
- [x] ARINÇ DEMİR
- [x] ASUDE EBRAR KIZILOĞLU (#89)
- [x] GÜNEY YÜKSEL (#86)
- [ ] HALİL UTKU ÇELİK
- [x] ÖZGÜR DENİZ DEMİR
- [x] RAMAZAN ONUR ACAR
- [ ] SEMİH YILMAZ
- [x] SÜLEYMAN EMİR TAŞAN (#101)

## Estimated Time
25 mins per member.

## Deadline
Date(17/03/2024) - 22.59

## Reviewer
@ramazanoacar  - Deadline of the review(18/03/2024 - 18.00)

**Comment by ebrarkiziloglu** [comment]
I have discovered that once we add an issue to a certain Project, the issue is shown at the bottom of the issues list on the Roadmap View. We can hold the issue and drag it from bottom to the top to sort the issues according to the creation date. The issue numbers is also shown in this view (the red marked part below). This can help us sort the issues and generate an accurate roadmap view for our previous issues!

![Screenshot 2024-03-16 at 21 06 02](https://github.com/bounswe/bounswe2024group5/assets/83813907/e4761b7c-c09e-460c-8bf4-610ab26ada8e)

**Comment by arincdemir** [comment]
@ebrarkiziloglu I'm not sure if that is necessary. We can easily use the sort option at the top right of your screen to sort them according to their starting dates.

**Comment by ebrarkiziloglu** [comment]
That is great @arincdemir, thank you for pointing this out!

**Comment by ebrarkiziloglu** [comment]
I have added a VERY tentative plan for the upcoming 9 weeks we have, according to the feedback from the TA and my research online. They can be seen at the bottom of the [roadmap](https://github.com/orgs/bounswe/projects/52/views/4).
@ramazanoacar this issue is ready to be reviewed now.

**Comment by ramazanoacar** [comment]
@ebrarkiziloglu issues regarding the upcoming weeks look fine. However, there seems some group members who haven't updated their issues. I don't know what should we do in this condition? Do you have any suggestions for review?

**Comment by ebrarkiziloglu** [comment]
> @ebrarkiziloglu issues regarding the upcoming weeks look fine. However, there seems some group members who haven't updated their issues. I don't know what should we do in this condition? Do you have any suggestions for review?

Thank you for the review @ramazanoacar! 
This issue is now on hold until the missing tasks are complete.
@odenizddd @semihYILMAZ37 @HutkuC

**Comment by ebrarkiziloglu** [comment]
As we submitted the project plan, this issue is now complete. 
@ramazanoacar could you please review it once more?

**Comment by ramazanoacar** [comment]
@ebrarkiziloglu yes I believe there is nothing we can do now. Thanks for your effort
