### ISSUE TITLE
Create the mockups for the website

### ISSUE THREAD

**Issue by Ultiminati** [bounswe/bounswe2024group5#98]
### Issue Description

Create a design that meets the requirements of the project.

### Tasks

- [x] Mockup for the feed, with two posts in it.
- [x] Mockup for the login and registration pages.
- [x] Mockup for the account page.

### Estimated Time

180

### Deadline

17.03.2024

### Reviewer

@SouthAscend - Deadline of the review (18/03/2024 - 15.00)

**Comment by Ultiminati** [comment]
The issue can be closed after @HutkuC does the mockup for the account details page.

**Comment by SouthAscend** [comment]
Can you update the labels accordingly?

**Comment by Ultiminati** [comment]
> Can you update the labels accordingly?

Done.

**Comment by HutkuC** [comment]
Mockup for **user profile** is done.
https://www.figma.com/file/GjbnrxjfZTccUoVZrLDC1p/CmpE-352-Mockup?type=design&node-id=0%3A1&mode=design&t=phNwpPIV7sAhYCCY-1

**Comment by SouthAscend** [comment]
Everything looks good.
